#!/bin/sh
set -e

"$BASELOC"/o/web/yices2/yices2*/configure --prefix="$COSMOS"\
    CFLAGS="-O3 -g" \
    CPPFLAGS="-I$COSMOS/include/kissat -DHAVE_KISSAT" \
    LDFLAGS="-L$COSMOS/lib" \
    LIBS="-lkissat"
