#!/bin/sh
set -e

cp -r "$BASELOC"/o/cli/yices2/yices2-*/* .
./configure --prefix="$COSMOS" \
    CFLAGS="-O3 -g" \
    CPPFLAGS="-I$COSMOS/include/kissat -DHAVE_KISSAT" \
    LDFLAGS="-L$COSMOS/lib" \
    LIBS="-lkissat"
