on:
  push:
    tags:
      - z*
  workflow_dispatch:
  release:
    types: [created]

name: Handle Release
jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        result: [lang, compress, web, aarch64-gcc, x86_64-gcc, cli, datasette, pypack1, editor, llvm]
    name: ${{ matrix.result }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: support ape bins and SSL things
        run: bash ./.github/scripts/setup
      - name: build Cosmo
        run: bash ./.github/scripts/cosmo
      - name: build ${{ matrix.result }}
        env:
          COLLECTION: yes
        run: bash ./.github/scripts/collectbuild ${{ matrix.result }}
      - name: collect into zip
        env:
          ZFILENAME: ${{ matrix.result }}
        run: bash ./.github/scripts/collectzip
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: "${{ matrix.result }}*.zip"
          fail_on_unmatched_files: true
          prerelease: true
